import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';
import { EvaluationResult, EvaluationInput, AppSettings } from '../types';

export type EvaluationStage = 'idle' | 'analyzing' | 'correctness' | 'hallucination' | 'computing' | 'generating' | 'complete';

export interface StageInfo {
  stage: EvaluationStage;
  label: string;
  progress: number;
}

interface EvaluationContextType {
  currentEvaluation: EvaluationResult | null;
  history: EvaluationResult[];
  evaluationError: string | null;
  settings: AppSettings;
  isEvaluating: boolean;
  currentStage: StageInfo;
  evaluate: (input: EvaluationInput) => Promise<void>;
  clearCurrentEvaluation: () => void;
  updateSettings: (settings: Partial<AppSettings>) => void;
  deleteFromHistory: (id: string) => void;
  addHistoryItems: (items: EvaluationResult[]) => void;
}

const EvaluationContext = createContext<EvaluationContextType | undefined>(undefined);

const stages: StageInfo[] = [
  { stage: 'analyzing', label: 'Analyzing Response...', progress: 10 },
  { stage: 'correctness', label: 'Checking Correctness...', progress: 30 },
  { stage: 'hallucination', label: 'Detecting Hallucinations...', progress: 50 },
  { stage: 'computing', label: 'Computing Scores...', progress: 70 },
  { stage: 'generating', label: 'Generating Report...', progress: 90 },
  { stage: 'complete', label: 'Complete!', progress: 100 },
];
export function EvaluationProvider({ children }: { children: ReactNode }) {
  const [currentEvaluation, setCurrentEvaluation] = useState<EvaluationResult | null>(null);
  const [history, setHistory] = useState<EvaluationResult[]>([]);
  const [evaluationError, setEvaluationError] = useState<string | null>(null);
  const [settings, setSettings] = useState<AppSettings>({
    darkMode: true,
    framework: 'RAGAS',
  });
  const [isEvaluating, setIsEvaluating] = useState(false);
  const [currentStage, setCurrentStage] = useState<StageInfo>({ stage: 'idle', label: '', progress: 0 });

   const extractScore = (value: unknown): number => {
    if (typeof value === 'number' && Number.isFinite(value)) return value;
    if (typeof value !== 'string') return 0;
    const match = value.match(/-?\d+(?:\.\d+)?/);
    return match ? Number(match[0]) : 0;
   };

 const evaluate = useCallback(async (input: EvaluationInput) => {
  setEvaluationError(null);
  setIsEvaluating(true);
  setCurrentStage(stages[0]);

  for (let i = 0; i < stages.length - 1; i++) {
    await new Promise((resolve) => setTimeout(resolve, 800));
    setCurrentStage(stages[i]);
  }

  await new Promise((resolve) => setTimeout(resolve, 600));
  setCurrentStage(stages[stages.length - 1]);

  await new Promise((resolve) => setTimeout(resolve, 400));

  try {
   const response = await fetch("http://127.0.0.1:8000/evaluate", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    question: input.question,
    response: input.aiResponse,
    reference: input.referenceAnswer || "",
  }),
});

if (!response.ok) {
  const errorResult = await response.json().catch(() => ({}));
  throw new Error(errorResult.detail || `Evaluation failed (${response.status}).`);
}

const apiResult = await response.json();
const formatOutput = (text: unknown) => String(text ?? '')
    .replace(/Reason:/g, "\nReason:\n")
    .replace(/\n{3,}/g, "\n\n");

console.log("API Result:", apiResult);
console.log("Verdict:", apiResult.verdict);

    const relevance = extractScore(apiResult.relevance);
    const accuracy = extractScore(apiResult.accuracy);
    const hallucination = extractScore(apiResult.hallucination);
    const completeness = extractScore(apiResult.completeness);

    const overall = extractScore(apiResult.verdict?.overall_score);

    const evaluationResult: EvaluationResult = {
      id: Date.now().toString(),

      question: input.question,

      aiResponse: input.aiResponse,

      referenceAnswer: input.referenceAnswer || "Not Provided",

      sourceDocument: input.sourceDocument?.name,

      metrics: {
        correctness: accuracy * 10,
        relevance: relevance * 10,
        faithfulness: 100,
        completeness: completeness * 10,
        fluency: 100,
        hallucinationRisk: hallucination * 10,
        overallScore: overall,
      },
      verdict: {
        overall_score: extractScore(apiResult.verdict?.overall_score),
        verdict: apiResult.verdict?.verdict || 'NEEDS IMPROVEMENT',
        summary: apiResult.verdict?.summary || apiResult.verdict?.reason || '',
      },
      hallucinationLevel:
        hallucination <= 2
          ? "Low"
          : hallucination <= 6
          ? "Medium"
          : "High",

    suggestions: [
      formatOutput(apiResult.relevance),
      formatOutput(apiResult.accuracy),
      formatOutput(apiResult.hallucination),
      formatOutput(apiResult.completeness),
    ],

      recommendations: [
        "Generated by AI Judge Agents",
      ],

      evaluatedAt: new Date(),
    };

   setCurrentEvaluation(evaluationResult);

setHistory((prev) => [evaluationResult, ...prev]);

  } catch (err) {
    console.error(err);
    setEvaluationError(err instanceof Error ? err.message : 'Unable to complete evaluation.');
  }

  setIsEvaluating(false);

  setCurrentStage({
    stage: "idle",
    label: "",
    progress: 0,
  });

}, []);

  const clearCurrentEvaluation = useCallback(() => {
    setCurrentEvaluation(null);
  }, []);

  const updateSettings = useCallback((newSettings: Partial<AppSettings>) => {
    setSettings((prev) => ({ ...prev, ...newSettings }));
  }, []);

  const addHistoryItems = useCallback((items: EvaluationResult[]) => {
    setHistory((prev) => {
      const existingIds = new Set(prev.map((item) => item.id));
      const newItems = items.filter((item) => !existingIds.has(item.id));
      return [...newItems, ...prev];
    });
  }, []);

  const deleteFromHistory = useCallback((id: string) => {
    setHistory((prev) => prev.filter((item) => item.id !== id));
  }, []);

  return (
    <EvaluationContext.Provider
      value={{
        currentEvaluation,
        history,
        evaluationError,
        settings,
        isEvaluating,
        currentStage,
        evaluate,
        clearCurrentEvaluation,
        updateSettings,
        deleteFromHistory,
        addHistoryItems,
      }}
    >
      {children}
    </EvaluationContext.Provider>
  );
}

export function useEvaluation() {
  const context = useContext(EvaluationContext);
  if (!context) {
    throw new Error('useEvaluation must be used within an EvaluationProvider');
  }
  return context;
}
