import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';
import { EvaluationResult, EvaluationInput, AppSettings, EvaluationMetrics } from '../types';

export type EvaluationStage = 'idle' | 'analyzing' | 'correctness' | 'hallucination' | 'computing' | 'generating' | 'complete';

export interface StageInfo {
  stage: EvaluationStage;
  label: string;
  progress: number;
}

interface EvaluationContextType {
  currentEvaluation: EvaluationResult | null;
  history: EvaluationResult[];
  settings: AppSettings;
  isEvaluating: boolean;
  currentStage: StageInfo;
  evaluate: (input: EvaluationInput) => Promise<void>;
  clearCurrentEvaluation: () => void;
  updateSettings: (settings: Partial<AppSettings>) => void;
  deleteFromHistory: (id: string) => void;
}

const EvaluationContext = createContext<EvaluationContextType | undefined>(undefined);

const stages: StageInfo[] = [
  { stage: 'analyzing', label: 'Analyzing Response...', progress: 10 },
  { stage: 'correctness', label: 'Checking Correctness...', progress: 30 },
  { stage: 'hallucination', label: 'Detecting Hallucinations...', progress: 50 },
  { stage: 'computing', label: 'Computing Scores...', progress: 70 },
  { stage: 'generating', label: 'Generating Report...', progress: 90 },
  { stage: 'complete', label: 'Complete!', progress: 100 },
];
export function EvaluationProvider({ children }: { children: ReactNode }) {
  const [currentEvaluation, setCurrentEvaluation] = useState<EvaluationResult | null>(null);
  const [history, setHistory] = useState<EvaluationResult[]>([]);
  const [settings, setSettings] = useState<AppSettings>({
    darkMode: true,
    framework: 'RAGAS',
  });
  const [isEvaluating, setIsEvaluating] = useState(false);
  const [currentStage, setCurrentStage] = useState<StageInfo>({ stage: 'idle', label: '', progress: 0 });

 const evaluate = useCallback(async (input: EvaluationInput) => {
  setIsEvaluating(true);
  setCurrentStage(stages[0]);

  for (let i = 0; i < stages.length - 1; i++) {
    await new Promise((resolve) => setTimeout(resolve, 800));
    setCurrentStage(stages[i]);
  }

  await new Promise((resolve) => setTimeout(resolve, 600));
  setCurrentStage(stages[stages.length - 1]);

  await new Promise((resolve) => setTimeout(resolve, 400));

  try {
   const response = await fetch("http://127.0.0.1:8000/evaluate", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    question: input.question,
    response: input.aiResponse,
    reference: input.referenceAnswer || "",
  }),
});

const apiResult = await response.json();

console.log(apiResult);

    const relevance =
      Number(apiResult.relevance.match(/\d+/)?.[0]) || 0;

    const accuracy =
      Number(apiResult.accuracy.match(/\d+/)?.[0]) || 0;

    const hallucination =
      Number(apiResult.hallucination.match(/\d+/)?.[0]) || 0;

    const overall =
      Math.round(
        ((relevance + accuracy + (10 - hallucination)) / 3) * 10
      );

    const evaluationResult: EvaluationResult = {
      id: Date.now().toString(),

      question: input.question,

      aiResponse: input.aiResponse,

      referenceAnswer: input.referenceAnswer || "Not Provided",

      sourceDocument: input.sourceDocument?.name,

      metrics: {
        correctness: accuracy,
        relevance: relevance,
        faithfulness: 100,
        completeness: 100,
        fluency: 100,
        hallucinationRisk: hallucination,
        overallScore: overall,
      },

      hallucinationLevel:
        hallucination <= 2
          ? "Low"
          : hallucination <= 6
          ? "Medium"
          : "High",

    suggestions: [
  apiResult.relevance.replace("Reason:", "\nReason:"),
  apiResult.accuracy.replace("Reason:", "\nReason:"),
  apiResult.hallucination.replace("Reason:", "\nReason:"),
],

      recommendations: [
        "Generated by AI Judge Agents",
      ],

      evaluatedAt: new Date(),
    };

   setCurrentEvaluation(evaluationResult);

setHistory((prev) => [evaluationResult, ...prev]);

  } catch (err) {
    console.error(err);
  }

  setIsEvaluating(false);

  setCurrentStage({
    stage: "idle",
    label: "",
    progress: 0,
  });

}, []);

  const clearCurrentEvaluation = useCallback(() => {
    setCurrentEvaluation(null);
  }, []);

  const updateSettings = useCallback((newSettings: Partial<AppSettings>) => {
    setSettings((prev) => ({ ...prev, ...newSettings }));
  }, []);

  const deleteFromHistory = useCallback((id: string) => {
    setHistory((prev) => prev.filter((item) => item.id !== id));
  }, []);

  return (
    <EvaluationContext.Provider
      value={{
        currentEvaluation,
        history,
        settings,
        isEvaluating,
        currentStage,
        evaluate,
        clearCurrentEvaluation,
        updateSettings,
        deleteFromHistory,
      }}
    >
      {children}
    </EvaluationContext.Provider>
  );
}

export function useEvaluation() {
  const context = useContext(EvaluationContext);
  if (!context) {
    throw new Error('useEvaluation must be used within an EvaluationProvider');
  }
  return context;
}
